### ISSUE TITLE
Issue after installing

### ISSUE THREAD

**Issue by TristanKnot** [Kyubyong/g2p#15]
I've installed g2p_en on my macOS system using setup.py

I created a test_g2p.py file containing the sample code provided in the README. When I run **python test_g2p.py** I receive the error below. I'm using python 3.7.

Any idea of how I proceed? 

> Traceback (most recent call last):
  File "test_g2p.py", line 1, in <module>
    from g2p_en import G2p
  File "/Users/Tristan/anaconda3/lib/python3.7/site-packages/g2p_en-2.0.0-py3.7.egg/g2p_en/__init__.py", line 1, in <module>
    from .g2p import G2p
  File "/Users/Tristan/anaconda3/lib/python3.7/site-packages/g2p_en-2.0.0-py3.7.egg/g2p_en/g2p.py", line 21, in <module>
    nltk.data.find('taggers/averaged_perceptron_tagger.zip')
  File "/Users/Tristan/anaconda3/lib/python3.7/site-packages/nltk/data.py", line 660, in find
    return ZipFilePathPointer(p, zipentry)
  File "/Users/Tristan/anaconda3/lib/python3.7/site-packages/nltk/compat.py", line 228, in _decorator
    return init_func(*args, **kwargs)
  File "/Users/Tristan/anaconda3/lib/python3.7/site-packages/nltk/data.py", line 506, in __init__
    zipfile = OpenOnDemandZipFile(os.path.abspath(zipfile))
  File "/Users/Tristan/anaconda3/lib/python3.7/site-packages/nltk/compat.py", line 228, in _decorator
    return init_func(*args, **kwargs)
  File "/Users/Tristan/anaconda3/lib/python3.7/site-packages/nltk/data.py", line 1055, in __init__
    zipfile.ZipFile.__init__(self, filename)
  File "/Users/Tristan/anaconda3/lib/python3.7/zipfile.py", line 1222, in __init__
    self._RealGetContents()
  File "/Users/Tristan/anaconda3/lib/python3.7/zipfile.py", line 1289, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file

**Comment by TristanKnot** [comment]
It turns out the nltk package was not importing one of the zip files correctly, specifically "'taggers/averaged_perceptron_tagger.zip". Posuer's solution on SO seemed to resolve the error (https://stackoverflow.com/a/38931681/7147480).
